name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install requirements
        run: pip install --user -r requirements.txt
      - name: Execute linter
        run: make lint
