name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: actions/setup-python@v1
          python-version: 3.7
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run linter
        run: make lint
